service: punjaci
frameworkVersion: "3"

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

resources:
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: personal-website
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref WebsiteBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: !Join ["", ["arn::aws::s3:::", !Ref WebsiteBucket, "/*"]]

